// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uibofopswuqljvqtuamw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpYm9mb3Bzd3VxbGp2cXR1YW13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzA3NDAsImV4cCI6MjA2MTYwNjc0MH0.Fj3wx4PH7QIbckzs8W7DexVONW-0iMqZcVWHeszQRqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);